package TwentyOnePoint;

import java.util.List;

public class CardPoll
{
    public static final List<Card> cards = List.of(
        new Card(CardColor.clubs,    CardPoint.A),
        new Card(CardColor.diamonds, CardPoint.A),
        new Card(CardColor.hearts,   CardPoint.A),
        new Card(CardColor.spades,   CardPoint.A),
        new Card(CardColor.clubs,    CardPoint.C2),
        new Card(CardColor.diamonds, CardPoint.C2),
        new Card(CardColor.hearts,   CardPoint.C2),
        new Card(CardColor.spades,   CardPoint.C2),
        new Card(CardColor.clubs,    CardPoint.C3),
        new Card(CardColor.diamonds, CardPoint.C3),
        new Card(CardColor.hearts,   CardPoint.C3),
        new Card(CardColor.spades,   CardPoint.C3),
        new Card(CardColor.clubs,    CardPoint.C4),
        new Card(CardColor.diamonds, CardPoint.C4),
        new Card(CardColor.hearts,   CardPoint.C4),
        new Card(CardColor.spades,   CardPoint.C4),
        new Card(CardColor.clubs,    CardPoint.C5),
        new Card(CardColor.diamonds, CardPoint.C5),
        new Card(CardColor.hearts,   CardPoint.C5),
        new Card(CardColor.spades,   CardPoint.C5),
        new Card(CardColor.clubs,    CardPoint.C6),
        new Card(CardColor.diamonds, CardPoint.C6),
        new Card(CardColor.hearts,   CardPoint.C6),
        new Card(CardColor.spades,   CardPoint.C6),
        new Card(CardColor.clubs,    CardPoint.C7),
        new Card(CardColor.diamonds, CardPoint.C7),
        new Card(CardColor.hearts,   CardPoint.C7),
        new Card(CardColor.spades,   CardPoint.C7),
        new Card(CardColor.clubs,    CardPoint.C8),
        new Card(CardColor.diamonds, CardPoint.C8),
        new Card(CardColor.hearts,   CardPoint.C8),
        new Card(CardColor.spades,   CardPoint.C8),
        new Card(CardColor.clubs,    CardPoint.C9),
        new Card(CardColor.diamonds, CardPoint.C9),
        new Card(CardColor.hearts,   CardPoint.C9),
        new Card(CardColor.spades,   CardPoint.C9),
        new Card(CardColor.clubs,    CardPoint.C10),
        new Card(CardColor.diamonds, CardPoint.C10),
        new Card(CardColor.hearts,   CardPoint.C10),
        new Card(CardColor.spades,   CardPoint.C10),
        new Card(CardColor.clubs,    CardPoint.J),
        new Card(CardColor.diamonds, CardPoint.J),
        new Card(CardColor.hearts,   CardPoint.J),
        new Card(CardColor.spades,   CardPoint.J),
        new Card(CardColor.clubs,    CardPoint.Q),
        new Card(CardColor.diamonds, CardPoint.Q),
        new Card(CardColor.hearts,   CardPoint.Q),
        new Card(CardColor.spades,   CardPoint.Q),
        new Card(CardColor.clubs,    CardPoint.K),
        new Card(CardColor.diamonds, CardPoint.K),
        new Card(CardColor.hearts,   CardPoint.K),
        new Card(CardColor.spades,   CardPoint.K)
    );
}
